blank_issues_enabled: true
contact_links:
  - name: Read the book
    url: https://laurence-wilse-samson.gitbook.io/textbooks/the-american-economy/
    about: The published version of the manuscript in this repository.
